//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyDraw.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MYDRAWTYPE                  129
#define ID_TOOL_RECTANGLE               32771
#define ID_TOOL_ELLIPSE                 32772
#define ID_TOOL_TRANSPARENT             32773
#define ID_EDIT_ERASE                   32774
#define ID_EDIT_ERASEALL                32775
#define ID_EDIT_ERASE_ALL               32776
#define ID_COLOR_BLACK                  32795
#define ID_COLOR_BLUE                   32796
#define ID_COLOR_GREEN                  32797
#define ID_COLOR_CYAN                   32798
#define ID_COLOR_RED                    32799
#define ID_COLOR_MAGENTA                32800
#define ID_COLOR_YELLOW                 32801
#define ID_COLOR_WHITE                  32802
#define ID_COLOR_DKGRAY                 32803
#define ID_COLOR_LTGRAY                 32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
