////////////////////////////////
//
//  sizes.cpp
//
////////////////////////////////

#include <iostream.h>

void main()
{
	cout << "Sizes of common C++ data types in Visual C++" << endl << endl;

	cout << "int          " << sizeof(int) << endl;
	cout << "short int    " << sizeof(short) << endl;
	cout << "long int     " << sizeof(long) << endl;
	cout << "char         " << sizeof(char) << endl;
	cout << "float        " << sizeof(float) << endl;
	cout << "double       " << sizeof(double) << endl;
	cout << "long double  " << sizeof(long double) << endl;
	cout << "bool         " << sizeof(bool) << endl;



}