//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyDraw.rc
//
#define IDD_ABOUTBOX                    100
#define ID_UNDO_DRAW                    101
#define ID_REDO_DRAW                    102
#define ID_UNDO_ERASE                   103
#define ID_UNDO_ERASE_ALL               104
#define ID_UNDO_TITLE                   105
#define ID_REDO_ERASE                   106
#define CG_IDS_PHYSICAL_MEM             107
#define CG_IDS_DISK_SPACE               108
#define CG_IDS_DISK_SPACE_UNAVAIL       109
#define IDR_MAINFRAME                   128
#define IDR_MYDRAWTYPE                  129
#define IDR_DRAWING                     134
#define IDD_DRAWING_TITLE               136
#define IDD_PS_LINE                     137
#define IDD_PS_SHAPE                    138
#define IDR_MENU1                       140
#define IDC_DRAWING_TITLE               1000
#define IDC_EDIT1                       1001
#define IDC_SPIN1                       1002
#define IDC_COMBO1                      1003
#define IDC_RADIO1                      1004
#define IDC_RADIO2                      1005
#define IDC_CHECK1                      1006
#define IDC_PHYSICAL_MEM                1007
#define IDC_DISK_SPACE                  1008
#define IDC_STATIC_COLOR                1009
#define ID_TOOL_RECTANGLE               32771
#define ID_TOOL_ELLIPSE                 32772
#define ID_TOOL_TRANSPARENT             32773
#define ID_EDIT_ERASE                   32774
#define ID_EDIT_ERASEALL                32775
#define ID_EDIT_ERASE_ALL               32776
#define ID_COLOR_BLACK                  32795
#define ID_COLOR_BLUE                   32796
#define ID_COLOR_GREEN                  32797
#define ID_COLOR_CYAN                   32798
#define ID_COLOR_RED                    32799
#define ID_COLOR_MAGENTA                32800
#define ID_COLOR_YELLOW                 32801
#define ID_COLOR_WHITE                  32802
#define ID_COLOR_DKGRAY                 32803
#define ID_COLOR_LTGRAY                 32804
#define ID_TOOL_SELECTION               32806
#define ID_EDIT_DRAWING_TITLE           32809
#define ID_TOOL_CUSTOM_COLOR            32810
#define ID_TOOL_SETTINGS                32811
#define ID_VIEW_TOOLBAR_STD             32812
#define ID_VIEW_TOOLBAR_DRAWING         32813
#define ID_TOOL_BRING_FWD               32814
#define ID_TOOL_SEND_BEHIND             32815
#define ID_TOOL_BRING_FRONT             32816
#define ID_TOOL_SEND_BACK               32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
